---
kind: Deployment
apiVersion: apps/v1beta2
metadata:
  labels:
    app: grafana
  name: grafana
  namespace: default
spec:
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: grafana
  template:
    metadata:
      labels:
        app: grafana
    spec:
      nodeSelector:
        yhf: master01
      containers:
        - name: grafana
          image: harbor.shinezone.com/shinezonetest/grafana:1.0
          env:
            - name: GF_AUTH_BASIC_ENABLED
              value: "true"
            - name: GF_AUTH_ANONYMOUS_ENABLED
              value: "false"
          readinessProbe:
            httpGet:
              path: /login
              port: 3000
          volumeMounts:
            - mountPath: /var/lib/grafana
              name: grafana-data-local
          ports:
            - containerPort: 3000
              protocol: TCP
      volumes:
        - name: grafana-data-local
          hostPath:
            path: "/data/grafana_data"  #备注：mkdir -p /data/grafana_data;chmod 777 -R /data/grafana_data 记住一定要赋权，不然报错  
---
kind: Service
apiVersion: v1
metadata:
  labels:
    app: grafana
  name: grafana-service
  namespace: default
spec:
  ports:
    - port: 3000
      targetPort: 3000
  selector:
    app: grafana
  type: NodePort
