apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  labels:
    prometheus: k8s
    role: alert-rules
  name: prometheus-kubelet-rules
  namespace: monitoring
spec:
  groups:
  - name: Kubelet监控
    rules:
    - alert: K8S Kubelet Down
      annotations:
        detail:  "你有一台NodeName为：{{$labels.node}}, 实例IP端口：{{$labels.instance}}，Kubelet Down (当前值: {{ $value }})"
        summary: "{{$labels.instance}}: Kubelet Down"
      expr: |
        up{endpoint="https-metrics",job="kubelet",namespace="kube-system",service="kubelet"} == 0
      for: 1m
      labels:
        severity: 严重